## Name: Tokyo Night Dark

# Special
foreground = #c0caf5
background = #1a1b26
cursor     = #c0caf5
# Black
color0  = #15161E
color8  = #414868
# Red
color1  = #d9656e
color9  = #d9656e
# Green
color2  = #5ebe7a
color10 = #5ebe7a
# Yellow
color3  = #c4c06b
color11 = #c4c06b
# Blue
color4  = #7aa2f7
color12 = #7aa2f7
# Magenta
color5  = #bb7ad7
color13 = #bb7ad7
# Cyan
color14 = #7dcfff
color6  = #7dcfff
# White
color7  = #a9b1d6
color15 = #c0caf5
# Orange
color17 = #ff8e64
color16 = #ff8e64
